# Homework 8


**Concepts covered:**

numpy, array operations, linear algebra


**Instructions:**

Be sure to run each code block after you edit it to make sure it runs as expected. When you are done, we strongly recommend you run all the code from scratch (Runtime menu -> Restart and Run all) to make sure your current code works for all problems.

If your code raises an exception when run from scratch, it will interfere with the auto-grader process causing you to lose some or all points for this homework. Please ask for help on Piazza, attend office hours or schedule an appointment with your learning facilitator if you get stuck.

**Warning about AI:**

While we encourage you to use AI to generate practice problems, **we recommend against using generative AI in the strongest terms** to solve any part of this assignment. The goal of this assignment is for you to learn these concepts, and while using AI may help you obtain solutions to these problems, you will cheat yourself out of the learning that comes from working through the problems yourself.

**Sample Output:**

For each problem description, a sample output has been included to show what the expected output should be.
Some functions have test cases provided for you to test with, so no sample output has been included for those.


**Docstrings and Comments:**

Include a *documentation string* (docstring) for each function definition, as well as comments in the body of your code to explain each control structures (e.g., decision, loop), function call, or formula.

The following starter code will be used in several problems. Run the following cell before continuing.

In [1]:
# imports
import numpy as np

**Review Problem 1**

**Concept:** *Numpy arrays.*

**Task:**

Write a function `max_column_sum(a)` that takes a 2D numpy array and:

1. Computes the sum of each column

2. Returns the largest column sum (a number)

**Sample Output:**

Consider this array `a`:
```
a = np.array([[ 7, -2,  5, 1],
              [ 3,  4, -6, 9],
              [-1,  8,  2, 0]])
```
If we call the function `max_column_sum(a)`, it should return `10`.


In [2]:
# TO DO: WRITE YOUR SOLUTION HERE
def max_column_sum(a):
    '''Returns the highest sum of the columns in an Numpy array'''
    return a.sum(axis=0).max()


Test cases for problem 1

In [3]:
# WRITE YOUR TEST CASES HERE
a = np.array([[7, -2, 5, 1],
              [3, 4, -6, 9],
              [-1, 8, 2, 0]])

max_column_sum(a)

np.int64(10)

**Review Problem 2**

**Concept:** *Numpy arrays, if statement, loops.*

**Task:**

Write a function `check_row_sum(x, value)` that takes a 2D numpy array `x` and a number `value`, and returns:

* `True` if every row sum is within 0.001 of `value`

* `False` otherwise

**Sample Output:**

Consider this array `x`:

```
x = np.array([[2.0, 1.0, 3.0],
              [4.5, 0.5, 1.0],
              [1.2, 2.3, 2.5]])
```
If we call the function `check_row_sum(x, value)`, it should return `True`.


In [4]:
# TO DO: WRITE YOUR SOLUTION HERE
def check_row_sum(x, value):
    '''Checks that all rows sum within a tolerance level of a given value and returns either True or False'''
    total = x.sum(axis=1)
    upper = value + 0.001
    lower = value - 0.001
    if (total >= lower).all() and (total <= upper).all():
        return True
    else:
        return False


Test cases for problem 2

In [5]:
# WRITE YOUR TEST CASES HERE
x = np.array([[2.0, 1.0, 3.0],
              [4.5, 0.5, 1.0],
              [1.2, 2.3, 2.5]])

check_row_sum(x, 6.0)


True

**Problem 3**

**Concept:** *Numpy arrays.*

**Task:**

Write `check_value(a, b, value)` where:

* `a` is n×1

* `b` is 1D length m (or 1×m)

* Return `True` if any `a[i] + b[j] == value`, else `False`.

**Sample Output:**

Consider this array `a`:

```
a = np.array([[15],
              [60],
              [90]])
b = np.array([5, 25, 40])
```

If we call the function `check_value(a, b, value)`, it should return `True`.



In [6]:
# TO DO: WRITE YOUR SOLUTION HERE
def check_value(a, b, value):
    '''Checks that if the sum of any two values within two Numpy arrays are equal to a given value'''
    v = a + b
    if (value == v).any():
        return True
    else:
        return False


Test cases for problem 3

In [7]:
# WRITE YOUR TEST CASES HERE
a = np.array([[15],
              [60],
              [90]])

b = np.array([5, 25, 40])

check_value(a, b, 20)

True

**Problem 4**

**Concept:** *Numpy arrays.*

**Task:**

Write `dot_prod(a, b)` to compute the matrix product `a @ b` if dimensions are compatible.

If not compatible, print an error in this format: 'Incompatible dimensions: {shape of a} with {shape of b}.' and return `None`.

**Sample Output:**

Consider the following arrays `a` and `b`:

```
a = np.array([[1, 3, 2],
              [0, 5, 4]])
b = np.array([[2, 1],
              [0, 3],
              [1, 2]])
```

If we call the function `dot_prod(a, b)`, it should return:
```
[[ 4 14], [ 4 23]]

In [8]:
# TO DO: WRITE YOUR SOLUTION HERE

def dot_prod(a, b):
    '''Given compatible shapes, returns the dot product of two numpy arrays or returns an error message'''
    try:
        return a @ b
    except ValueError:
        print(f'Incompatible dimensions: {a.shape} with {b.shape}.')
        return None
    
    

Test cases for problem 4

In [9]:
# WRITE YOUR TEST CASES HERE

a = np.array([[1, 3, 2],
              [0, 5, 4]])
b = np.array([[2, 1],
              [0, 3],
              [1, 2],])

dot_prod(a, b)


array([[ 4, 14],
       [ 4, 23]])

**Problem 5**

**Concept:** *Numpy arrays, views, flatten.*


**Task:**

Write `view_proportion(x)` that:

* Returns `None` if `x` is not a view

* Otherwise returns `(# of elements visible in x) / (# of elements in original base array)`

**Sample Output:**

Consider the following:
```
base = np.arange(40)
x = base[10:30:2]  
```
If we call the function `view_proportion(x)`, it should return `0.25`.

There are 10 elements in the view and 40 in the base → 10/40 = 0.25


In [ ]:
# TO DO: WRITE YOUR SOLUTION HERE
def view_proportion(x):
   '''Returns the proportion of a numpy view given a numpy array converted to a view'''
   if x.base is None:
      return None
   
   xsize = x.size
   # print(xsize)
   basesize = x.base.size
   # print(basesize)
   
   return xsize / basesize
   



Test cases for problem 5

In [22]:
# WRITE YOUR TEST CASES HERE

base = np.arange(40)
x = base[10:30:2]
view_proportion(x)

10
40


0.25

**Problem 6**

**Concept:** *Numpy arrays, shape, flatten, slicing.*


**Task:**

Write `diagonal(x)` that returns the diagonal elements of a 2D array:
`x[0,0], x[1,1], x[2,2], ...` up to the largest valid diagonal.


**Sample Output:**

Consider this array `x`:
```
x = np.array([[ 4,  8,  1,  9],
              [ 7, -2,  6,  0],
              [ 5,  3, 10, 11],
              [12,  2, -1,  7]])
```
If we call the function `diagonal(x)` , it should return:
```
[ 4, -2, 10, 7]
```



In [16]:
# TO DO: WRITE YOUR SOLUTION HERE
def diagonal(x):
    return np.diag(x)
    



Test cases for problem 6

In [18]:
# WRITE YOUR TEST CASES HERE
x = np.array([[4, 8 ,1, 9],
              [7, -2, 6, 0],
              [5, 3, 10, 11],
              [12, 2, -1, 7]])

diagonal(x)


array([ 4, -2, 10,  7])

**Problem 7**

**Concept:** *Numpy arrays, broadcasting.*

**Task:**

The [$X + Y$ sorting problem](https://en.wikipedia.org/wiki/X_%2B_Y_sorting) considers pairs of numbers from two lists, $X$ and $Y$, and examines their sums.

Write a function `x_y_sorting(x, y)` that takes two 1D numpy arrays, `x` and `y`, as input.

The function should return a numpy array `z` where each element is the sum of an element from `x` and an element from `y`.

Specifically, the element in row `i` and column `j` of the output array should be:

$$
z[i,j]=x[i]+y[j]
$$

You should use numpy broadcasting to compute this efficiently rather than using nested loops.

The resulting array elements should be sorted in ascending order.

**Sample Output:**

Consider the following arrays `x` and `y`:
```
x = np.array([3, 7, -1, 0])
y = np.array([10, 2])
```
If we call the function `x_y_sorting(x, y)`, it should return:

```
[1, 2, 5, 9, 9, 10, 13, 17]
```


In [28]:
# TO DO: WRITE YOUR SOLUTION HERE
def x_y_sorting(x, y):
    '''Takes two 1D numpy arrays, x and y, and returns a new, z, array that is the sum of x and y and is also sorted'''
    z = x[:, None] + y
    return np.sort(z.flatten())
    


Test cases for problem 7

In [29]:
# WRITE YOUR TEST CASES HERE
x = np.array([3, 7, -1, 0])
y = np.array([10, 2])

x_y_sorting(x, y)


array([ 1,  2,  5,  9,  9, 10, 13, 17])

**Problem 8**

**Concept:** *Numpy arrays, hstack.*

**Task:**

Write a function `row_stats(x)` that takes an n×k numpy array as input.

The function should compute three statistics for each row of the array:

1. The minimum value of the row

2. The median value of the row

3. The maximum value of the row

The function should return a new n×3 numpy array where:

* Column 0 contains the minimum values

* Column 1 contains the median values

* Column 2 contains the maximum values

Use numpy functions such as `min`, `median`, and `max` with the appropriate axis, and combine the results using `np.hstack()`.


**Sample Output:**

Consider this array `x`:

```
x = np.array([[ 6,  2,  9,  4],
              [11,  3,  3,  8],
              [-5,  0,  5, 10]])
```

If we call the function `row_stats(x)`, it should return:
```
[[ 2. , 5. , 9. ], [ 3. , 5.5, 11. ], [-5. , 2.5, 10. ]]
```


In [37]:
# TO DO: WRITE YOUR SOLUTION HERE

def row_stats(x):
    '''Creates a new Numpy array that is a collection of calcuated statistics per each row'''
    min_stat = np.min(x, axis = 1).reshape(-1, 1)
    median_stat = np.median(x, axis = 1).reshape(-1, 1)
    max_stat = np.max(x, axis = 1).reshape(-1, 1)
    return np.hstack([min_stat, median_stat, max_stat])

Test cases for problem 8

In [39]:
# WRITE YOUR TEST CASES HERE

x = np.array([[6, 2, 9, 4],
              [11, 3, 3, 8],
              [-5, 0, 5, 10]])

row_stats(x)

array([[ 2. ,  5. ,  9. ],
       [ 3. ,  5.5, 11. ],
       [-5. ,  2.5, 10. ]])

**Problem 9**

**Concept:** *Numpy arrays, accumulator pattern.*

**Task:**

Write a function `harmonic_numbers(n)` that takes a positive integer `n` and returns a 1D numpy array of length `n` containing the first `n` harmonic numbers.

The harmonic numbers are defined as:

$$H_n = 1 + \frac{1}{2} + \frac{1}{3} + ... + \frac{1}{n}$$


Your array should contain:

* The first element equal to 1

* Each subsequent element computed using the previous value

Specifically:

$$
result[i] = result[i-1] + \frac{1}{i+1}
$$



Make sure to test your function with a large value such as `n = 100000` to confirm that your implementation runs efficiently.



**Sample Output:**

If we call the function `harmonic_numbers(n)` where `n = 6`, it should return:
```
[1. , 1.5 , 1.83333333, 2.08333333, 2.28333333, 2.45]
```


In [40]:
# TO DO: WRITE YOUR SOLUTION HERE

def harmonic_numbers(n):
    '''Returns a 1D numpy array of the first n harmonic numbers'''
    result = np.zeros(n, dtype=float)
    result[0] = 1.0  # H_1 = 1
    
    for i in range(1, n):
        result[i] = result[i-1] + 1 / (i + 1)
    
    return result
    

Test cases for problem 9

In [41]:
# WRITE YOUR TEST CASES HERE

n = 6
harmonic_numbers(n)

array([1.        , 1.5       , 1.83333333, 2.08333333, 2.28333333,
       2.45      ])

**Problem 10**

**Concept:** *Numpy arrays, accumulator pattern.*

Compute Fibonacci numbers

**Task:**

Write a function `fibonacci(n)` that returns a numpy array containing the first `n` Fibonacci numbers.

The Fibonacci sequence is defined as:

​$$
F_0 = 0, \quad F_1 = 1
$$

$$
F_n = F_{n-1} + F_{n-2}
$$


Your function should:

1. Create a numpy array of length `n`

2. Initialize the first two values

3. Use a loop to compute each subsequent value using the previous two numbers

The function should return the final array of Fibonacci numbers as integers.


**Sample Output:**

If we call the function `finobacci(n)` where `n = 10`, it should return:

```
[0, 1, 1, 2, 3, 5, 8, 13, 21, 34]
```


In [42]:
# TO DO: WRITE YOUR SOLUTION HERE

def fibonacci(n):
    '''Returns a 1D numpy array containing the first n Fibonacci numbers'''
    if n <= 0:
        return np.array([])
    elif n == 1:
        return np.array([0])
    
    result = np.zeros(n, dtype=int)
    result[0] = 0
    result[1] = 1
    
    for i in range(2, n):
        result[i] = result[i-1] + result[i-2]
    
    return result

Test cases for problem 10

In [43]:
# WRITE YOUR TEST CASES HERE

fibonacci(10)

array([ 0,  1,  1,  2,  3,  5,  8, 13, 21, 34])

**Problem 11**

**Concept:** *Numpy arrays, linear algebra.*

**Task:**

Write a function linear_regression(x, y) that computes the linear regression coefficients of y as a function of x using linear algebra.

The regression coefficients should be computed using the normal equation:

$$
\beta = (X^T X)^{-1} X^T y
$$

Where:

- $X$ is the matrix of input variables
- $y$ is the vector of observed outputs
- $\beta$ is the vector of regression coefficients
- $X^T$ is the transpose of $X$


Your function should:

1. Convert the inputs into numpy arrays or matrices if necessary

2. Compute the regression coefficients using numpy matrix multiplication

3. Return the coefficient vector

The returned coefficients represent the intercept and slope(s) of the regression model.


Use numpy operations such as matrix multiplication (`@`) and transpose (`.T`) to compute the result.


**Sample Output:**

1-variable regression with intercept column

Consider the following:
```
x = np.array([[1, 1],
              [1, 2],
              [1, 3],
              [1, 4],
              [1, 5]])
y = np.array([[9],
              [12],
              [15],
              [18],
              [21]])
```

If we call the function `linear_regression(x, y)`, then it should return:
```
[[6. ],
 [3. ]]
```

Meaning: intercept = 6, slope = 3

In [46]:
# TO DO: WRITE YOUR SOLUTION HERE

def linear_regression(x, y):
    '''Computes linear regression coefficients using the normal equation'''
    x = np.asarray(x, dtype=float)
    y = np.asarray(y, dtype=float).reshape(-1, 1)
    
    # Beta = (X^T X)^(-1) X^T y
    beta = np.linalg.inv(x.T @ x) @ x.T @ y
    
    return beta

Test cases for problem 11

In [47]:
# WRITE YOUR TEST CASES HERE

x = np.array([[1, 1],
              [1, 2],
              [1, 3],
              [1, 4],
              [1, 5]])
y = np.array([[9],
              [12],
              [15],
              [18],
              [21]])

linear_regression(x, y)

array([[6.],
       [3.]])